In [50]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### load data

In [54]:
df = pd.read_csv('data/mtp_16_17.csv', index_col='Date')
df

,location,MRN,Start,End,RBC IS,FFP IS,APL IS,CRYO IS,RBC TR,FFP TR,APL TR,CRYO TR,TOT TR UNITS,Wastage & Comments
Date,,,,,,,,,,,,,,
01/04/16,PW,3001789462,14:02,15:33,16.0,6.0,3.0,15.0,9.0,4.0,3.0,15.0,31.0,"1 pool cryo thawed, not used."
01/18/16,MAIN,3001862185,12:02,15:25,4.0,2.0,1.0,5.0,0.0,0.0,0.0,5.0,5.0,all units issued during MTP were returned. Poo...
01/20/16,PW,3001857124,0:00,1:34,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,3.0,"Twin 0.37kg, deceased. Emergency Release. 2 po..."
02/17/16,PW,8691963,10:48,11:41,4.0,4.0,1.0,0.0,4.0,4.0,1.0,0.0,9.0,2 pooled Cryo thawed not issued
03/05/16,MAIN,3001888890,19:57,?,6.0,2.0,1.0,0.0,2.0,1.0,1.0,0.0,4.0,"MTP was never called off, 4 Cryo wasted"
03/31/16,PW,3001900418,17:35,18:26,14.0,5.0,1.0,5.0,4.0,2.0,1.0,NaN,7.0,1 pool cryo
03/31/16,MAIN,3001583734,21:41,?,16.0,12.0,4.0,10.0,16.0,11.0,3.0,0.0,30.0,"MTP was never called off, patient was out of O..."
04/02/16,MAIN,8631511,20:20,23:56,6.0,2.0,0.0,0.0,0.0,2.0,0.0,0.0,2.0,NaN
04/04/16,MAIN,3001777212,17:10,18:02,10.0,4.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,RBC unit transfused was a partial unit (176cc)
04/08/16,MAIN,708832,17:30,18:07,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"35 y.o. cardiac patient, passed away in the EC..."
04/24/16,PW,1089764,13:29,14:31,14.0,4.0,1.0,5.0,5.0,2.0,0.0,5.0,12.0,NaN
04/26/16,PW,3001240349,9:33,11:15,12.0,5.0,4.0,15.0,10.0,5.0,4.0,10.0,29.0,2 units of pooled cryo wasted
05/02/16,PW,3001717683,18:37,19:05,5.0,2.0,0.0,0.0,3.0,2.0,0.0,0.0,5.0,1 unit of pooled cryo given after MTP deactiva...
05/02/16,PW,8111382,21:16,22:05,12.0,5.0,1.0,0.0,3.0,2.0,0.0,0.0,5.0,2 pool cryo wasted
05/03/16,MAIN,3001906139,20:25,22:15,8.0,3.0,1.0,0.0,4.0,1.0,1.0,0.0,6.0,2 pool cryo wasted
06/12/16,MAIN,3001503928,16:40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
06/17/16,MAIN,3001503928,9:46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
07/01/16,PW,3001801052,21:31,1:02,16.0,12.0,5.0,10.0,12.0,8.0,4.0,0.0,24.0,3 pooled Cryo returned
07/21/16,MAIN,3001835662,6:53,8:59,4.0,2.0,1.0,2.0,2.0,1.0,0.0,0.0,3.0,NaN
07/28/16,PW,3001879975,18:32,20:37,17.0,6.0,2.0,5.0,12.0,6.0,2.0,5.0,25.0,1 pool cryo wasted
9/17/2016,MAIN,3000942492,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10/16/16,MAIN,3001935816,8:07,10:26,16.0,11.0,2.0,1.0,11.0,9.0,2.0,0.0,22.0,1 pool cryo wasted
10/21/16,MAIN,3001876572,17:11,22:19,10.0,10.0,3.0,15.0,4.0,3.0,2.0,0.0,9.0,3 pool cryo wasted
11/04/16,MAIN,3001590103,13:07,NaN,10.0,5.0,3.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN
11/06/16,MAIN,3001723417,13:33,15:55,4.0,2.0,1.0,0.0,3.0,1.0,1.0,0.0,5.0,no wastage
11/13/16,PW,3002005070,23:00,23:30,8.0,6.0,1.0,15.0,8.0,6.0,0.0,15.0,29.0,"no wastage, used 1 more FFP and 1 Pool cryo"
11/15/16,MAIN,3002009195,12:30,15:09,10.0,4.0,2.0,0.0,6.0,2.0,2.0,0.0,10.0,thawd 1 pool cryo unused
11/17/16,PW,3001905973,13:33,13:36,8.0,3.0,0.0,0.0,3.0,0.0,0.0,0.0,3.0,1 APL picked up up right after deactivation.
12/14/16,MAIN,3000981511,18:57,22:12,4.0,2.0,1.0,0.0,0.0,1.0,1.0,0.0,2.0,NaN
12/16/16,PW,3002032988,22:38,0:18,16.0,5.0,1.0,10.0,4.0,3.0,1.0,10.0,18.0,"wasted 1 pool cryo; transfused 2 RBC, 2 APL, 1..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1/7/2017,MAIN,3002042220,21:44,NaN,NaN,NaN,NaN,NaN,10.0,4.0,1.0,5.0,20.0,NaN
1/22/2017,PW,3002049283,NaN,NaN,2.0,4.0,2.0,15.0,1.0,0.0,2.0,10.0,13.0,"10 cryo wasted, MTP was not called, transferre..."
1/23/2017,MAIN,3000814116,10:46,17:37,18.0,8.0,3.0,30.0,14.0,7.0,3.0,20.0,44.0,2 pool cryo wasted
1/26/2017,MAIN,3002051174,16:08,18:23,4.0,4.0,1.0,3.0,4.0,4.0,1.0,3.0,12.0,1 cryo wasted
1/27/2017,PW,3002000299,16:39,14:49,4.0,2.0,0.0,0.0,2.0,0.0,0.0,0.0,2.0,5 Cryo wasted
2/2/2017,MAIN,3001957557,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WTOR 11
2/13/2017,PW,3002059706,20:46,21:30,12.0,3.0,0.0,0.0,5.0,1.0,0.0,0.0,6.0,5 cryo wasted
3/30/2017,MAIN,3002059480,9:44,11:21,4.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,4.0,no wastage
4/19/2017,MAIN,8749067,20:00,22:00,19.0,13.0,10.0,0.0,10.0,7.0,8.0,0.0,25.0,MTP not called
5/26/2017,PW,3002098189,3:41,3:56,6.0,2.0,0.0,5.0,4.0,2.0,0.0,5.0,11.0,no wastage
6/26/2017,MAIN,3001662663,17:39,19:37,7.0,3.0,1.0,5.0,2.0,2.0,1.0,5.0,10.0,no wastage
6/29/2017,PW,8635087,16:56,17:38,NaN,NaN,NaN,NaN,4.0,3.0,2.0,5.0,14.0,"before activation(RBC=4,FFP=4,CRYO=20) 5 cryo ..."
6/30/2017,MAIN,3002120414,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7/6/2017,PW,3002115418,12:28,13:41,24.0,12.0,3.0,15.0,13.0,10.0,3.0,15.0,41.0,no wastage. Additional 2 pool cryo was transfu...
7/6/2017,MAIN,3001741265,17:23,0:49,4.0,3.0,1.0,0.0,3.0,3.0,1.0,0.0,7.0,"2 RBC EMR before MTP activation, 7 cryo wasted"
7/19/2017,MAIN,9146476,9:44,13:27,6.0,2.0,0.0,0.0,2.0,1.0,0.0,0.0,3.0,5 cryo wasted
7/27/2017,PW,3002132342,5:06,7:54,4.0,4.0,2.0,0.0,3.0,2.0,2.0,0.0,7.0,10 cryo wasted
8/2/2017,MAIN,8882468,4:38,6:23,NaN,NaN,NaN,NaN,3.0,2.0,0.0,0.0,5.0,5 cryo wasted
9/9/2017,MAIN,8892035,7:40,13:47,6.0,2.0,1.0,0.0,3.0,2.0,0.0,0.0,5.0,2 cryo wasted
10/8/2017,MAIN,8957994,2:27,8:10,NaN,NaN,NaN,NaN,2.0,1.0,0.0,0.0,3.0,no wastage
10/16/2017,PW,3001695085,18:40,21:49,NaN,NaN,NaN,NaN,12.0,6.0,3.0,30.0,51.0,no cryo wastage
10/17/2017,MAIN,3002173511,17:23,17:32,4.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,baby died
11/13/2017,MAIN,3002155024,10:12,11:43,NaN,NaN,NaN,NaN,8.0,4.0,1.0,NaN,13.0,5 cryo wasted
11/17/2017,PW,3002152687,13:02,13:22,NaN,NaN,NaN,NaN,6.0,2.0,NaN,NaN,8.0,5 cryo wasted
11/26/2017,PW,3002160499,2:00,4:00,NaN,NaN,NaN,NaN,8.0,4.0,2.0,20.0,34.0,6 pool (30) cryo wasted
12/5/2017,PW,3002118908,22:09,23:02,NaN,NaN,NaN,NaN,4.0,2.0,NaN,NaN,6.0,NaN
12/15/2017,PW,3002201467,5:00,6:16,8.0,2.0,1.0,30.0,6.0,2.0,1.0,30.0,39.0,2 pool cryo
12/21/2017,MAIN,3002202939,21:39,23:11,4.0,2.0,1.0,5.0,NaN,NaN,NaN,5.0,5.0,NaN
NaN,PW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,4.0,1.0,20.0,29.0,"before MTP activation 8635087, or 3002115418"
NaN,PW,NaN,NaN,NaN,4.0,2.0,2.0,10.0,NaN,NaN,NaN,NaN,18.0,3002132342 or 3001695085

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 64 entries, 01/04/16 to nan
Data columns (total 14 columns):
location              64 non-null object
MRN                   62 non-null object
Start                 58 non-null object
End                   53 non-null object
RBC IS                48 non-null float64
FFP IS                48 non-null float64
APL IS                47 non-null float64
CRYO IS               47 non-null float64
RBC TR                55 non-null float64
FFP TR                55 non-null float64
APL TR                53 non-null float64
CRYO TR               52 non-null float64
TOT TR UNITS          58 non-null float64
Wastage & Comments    50 non-null object
dtypes: float64(9), object(5)
memory usage: 7.5+ KB

In [57]:
df

,location,MRN,Start,End,RBC IS,FFP IS,APL IS,CRYO IS,RBC TR,FFP TR,APL TR,CRYO TR,TOT TR UNITS,Wastage & Comments
Date,,,,,,,,,,,,,,
01/04/16,PW,3001789462,14:02,15:33,16.0,6.0,3.0,15.0,9.0,4.0,3.0,15.0,31.0,"1 pool cryo thawed, not used."
01/18/16,MAIN,3001862185,12:02,15:25,4.0,2.0,1.0,5.0,0.0,0.0,0.0,5.0,5.0,all units issued during MTP were returned. Poo...
01/20/16,PW,3001857124,0:00,1:34,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,3.0,"Twin 0.37kg, deceased. Emergency Release. 2 po..."
02/17/16,PW,8691963,10:48,11:41,4.0,4.0,1.0,0.0,4.0,4.0,1.0,0.0,9.0,2 pooled Cryo thawed not issued
03/05/16,MAIN,3001888890,19:57,?,6.0,2.0,1.0,0.0,2.0,1.0,1.0,0.0,4.0,"MTP was never called off, 4 Cryo wasted"
03/31/16,PW,3001900418,17:35,18:26,14.0,5.0,1.0,5.0,4.0,2.0,1.0,NaN,7.0,1 pool cryo
03/31/16,MAIN,3001583734,21:41,?,16.0,12.0,4.0,10.0,16.0,11.0,3.0,0.0,30.0,"MTP was never called off, patient was out of O..."
04/02/16,MAIN,8631511,20:20,23:56,6.0,2.0,0.0,0.0,0.0,2.0,0.0,0.0,2.0,NaN
04/04/16,MAIN,3001777212,17:10,18:02,10.0,4.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,RBC unit transfused was a partial unit (176cc)
04/08/16,MAIN,708832,17:30,18:07,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"35 y.o. cardiac patient, passed away in the EC..."
04/24/16,PW,1089764,13:29,14:31,14.0,4.0,1.0,5.0,5.0,2.0,0.0,5.0,12.0,NaN
04/26/16,PW,3001240349,9:33,11:15,12.0,5.0,4.0,15.0,10.0,5.0,4.0,10.0,29.0,2 units of pooled cryo wasted
05/02/16,PW,3001717683,18:37,19:05,5.0,2.0,0.0,0.0,3.0,2.0,0.0,0.0,5.0,1 unit of pooled cryo given after MTP deactiva...
05/02/16,PW,8111382,21:16,22:05,12.0,5.0,1.0,0.0,3.0,2.0,0.0,0.0,5.0,2 pool cryo wasted
05/03/16,MAIN,3001906139,20:25,22:15,8.0,3.0,1.0,0.0,4.0,1.0,1.0,0.0,6.0,2 pool cryo wasted
06/12/16,MAIN,3001503928,16:40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
06/17/16,MAIN,3001503928,9:46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
07/01/16,PW,3001801052,21:31,1:02,16.0,12.0,5.0,10.0,12.0,8.0,4.0,0.0,24.0,3 pooled Cryo returned
07/21/16,MAIN,3001835662,6:53,8:59,4.0,2.0,1.0,2.0,2.0,1.0,0.0,0.0,3.0,NaN
07/28/16,PW,3001879975,18:32,20:37,17.0,6.0,2.0,5.0,12.0,6.0,2.0,5.0,25.0,1 pool cryo wasted
9/17/2016,MAIN,3000942492,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10/16/16,MAIN,3001935816,8:07,10:26,16.0,11.0,2.0,1.0,11.0,9.0,2.0,0.0,22.0,1 pool cryo wasted
10/21/16,MAIN,3001876572,17:11,22:19,10.0,10.0,3.0,15.0,4.0,3.0,2.0,0.0,9.0,3 pool cryo wasted
11/04/16,MAIN,3001590103,13:07,NaN,10.0,5.0,3.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN
11/06/16,MAIN,3001723417,13:33,15:55,4.0,2.0,1.0,0.0,3.0,1.0,1.0,0.0,5.0,no wastage
11/13/16,PW,3002005070,23:00,23:30,8.0,6.0,1.0,15.0,8.0,6.0,0.0,15.0,29.0,"no wastage, used 1 more FFP and 1 Pool cryo"
11/15/16,MAIN,3002009195,12:30,15:09,10.0,4.0,2.0,0.0,6.0,2.0,2.0,0.0,10.0,thawd 1 pool cryo unused
11/17/16,PW,3001905973,13:33,13:36,8.0,3.0,0.0,0.0,3.0,0.0,0.0,0.0,3.0,1 APL picked up up right after deactivation.
12/14/16,MAIN,3000981511,18:57,22:12,4.0,2.0,1.0,0.0,0.0,1.0,1.0,0.0,2.0,NaN
12/16/16,PW,3002032988,22:38,0:18,16.0,5.0,1.0,10.0,4.0,3.0,1.0,10.0,18.0,"wasted 1 pool cryo; transfused 2 RBC, 2 APL, 1..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1/7/2017,MAIN,3002042220,21:44,NaN,NaN,NaN,NaN,NaN,10.0,4.0,1.0,5.0,20.0,NaN
1/22/2017,PW,3002049283,NaN,NaN,2.0,4.0,2.0,15.0,1.0,0.0,2.0,10.0,13.0,"10 cryo wasted, MTP was not called, transferre..."
1/23/2017,MAIN,3000814116,10:46,17:37,18.0,8.0,3.0,30.0,14.0,7.0,3.0,20.0,44.0,2 pool cryo wasted
1/26/2017,MAIN,3002051174,16:08,18:23,4.0,4.0,1.0,3.0,4.0,4.0,1.0,3.0,12.0,1 cryo wasted
1/27/2017,PW,3002000299,16:39,14:49,4.0,2.0,0.0,0.0,2.0,0.0,0.0,0.0,2.0,5 Cryo wasted
2/2/2017,MAIN,3001957557,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WTOR 11
2/13/2017,PW,3002059706,20:46,21:30,12.0,3.0,0.0,0.0,5.0,1.0,0.0,0.0,6.0,5 cryo wasted
3/30/2017,MAIN,3002059480,9:44,11:21,4.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,4.0,no wastage
4/19/2017,MAIN,8749067,20:00,22:00,19.0,13.0,10.0,0.0,10.0,7.0,8.0,0.0,25.0,MTP not called
5/26/2017,PW,3002098189,3:41,3:56,6.0,2.0,0.0,5.0,4.0,2.0,0.0,5.0,11.0,no wastage
6/26/2017,MAIN,3001662663,17:39,19:37,7.0,3.0,1.0,5.0,2.0,2.0,1.0,5.0,10.0,no wastage
6/29/2017,PW,8635087,16:56,17:38,NaN,NaN,NaN,NaN,4.0,3.0,2.0,5.0,14.0,"before activation(RBC=4,FFP=4,CRYO=20) 5 cryo ..."
6/30/2017,MAIN,3002120414,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7/6/2017,PW,3002115418,12:28,13:41,24.0,12.0,3.0,15.0,13.0,10.0,3.0,15.0,41.0,no wastage. Additional 2 pool cryo was transfu...
7/6/2017,MAIN,3001741265,17:23,0:49,4.0,3.0,1.0,0.0,3.0,3.0,1.0,0.0,7.0,"2 RBC EMR before MTP activation, 7 cryo wasted"
7/19/2017,MAIN,9146476,9:44,13:27,6.0,2.0,0.0,0.0,2.0,1.0,0.0,0.0,3.0,5 cryo wasted
7/27/2017,PW,3002132342,5:06,7:54,4.0,4.0,2.0,0.0,3.0,2.0,2.0,0.0,7.0,10 cryo wasted
8/2/2017,MAIN,8882468,4:38,6:23,NaN,NaN,NaN,NaN,3.0,2.0,0.0,0.0,5.0,5 cryo wasted
9/9/2017,MAIN,8892035,7:40,13:47,6.0,2.0,1.0,0.0,3.0,2.0,0.0,0.0,5.0,2 cryo wasted
10/8/2017,MAIN,8957994,2:27,8:10,NaN,NaN,NaN,NaN,2.0,1.0,0.0,0.0,3.0,no wastage
10/16/2017,PW,3001695085,18:40,21:49,NaN,NaN,NaN,NaN,12.0,6.0,3.0,30.0,51.0,no cryo wastage
10/17/2017,MAIN,3002173511,17:23,17:32,4.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,baby died
11/13/2017,MAIN,3002155024,10:12,11:43,NaN,NaN,NaN,NaN,8.0,4.0,1.0,NaN,13.0,5 cryo wasted
11/17/2017,PW,3002152687,13:02,13:22,NaN,NaN,NaN,NaN,6.0,2.0,NaN,NaN,8.0,5 cryo wasted
11/26/2017,PW,3002160499,2:00,4:00,NaN,NaN,NaN,NaN,8.0,4.0,2.0,20.0,34.0,6 pool (30) cryo wasted
12/5/2017,PW,3002118908,22:09,23:02,NaN,NaN,NaN,NaN,4.0,2.0,NaN,NaN,6.0,NaN
12/15/2017,PW,3002201467,5:00,6:16,8.0,2.0,1.0,30.0,6.0,2.0,1.0,30.0,39.0,2 pool cryo
12/21/2017,MAIN,3002202939,21:39,23:11,4.0,2.0,1.0,5.0,NaN,NaN,NaN,5.0,5.0,NaN
NaN,PW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,4.0,1.0,20.0,29.0,"before MTP activation 8635087, or 3002115418"
NaN,PW,NaN,NaN,NaN,4.0,2.0,2.0,10.0,NaN,NaN,NaN,NaN,18.0,3002132342 or 3001695085